FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY . /usr/share/nginx/html
COPY docker-entrypoint.sh /docker-entrypoint.d/99-xmeme-config.sh
RUN chmod +x /docker-entrypoint.d/99-xmeme-config.sh
