version: "3.7"
sudo: required
language: python

install:
  - pip install package

services:
    web:
        build: ./backend/src
        ports:
          - 8081:8081
        depends_on:
          - api

    api:
        build: backend
        environment:
          - PORT=8081
        ports:
          - 8081:8081

script:
  - bash ./scripts/run_server.sh